### ISSUE TITLE
0.4.1 incompatible with Kotlin 1.7.21

### ISSUE THREAD

**Issue by rbraeunlich** [ryandens/javaagent-gradle-plugin#33]
Hello,
it seems like the new 0.4.1 release of your library is incompatible with Kotlin 1.7(.21).
My projects all crash in the gradle build step with the error 
```
Caused by: java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.incremental.FileUtilsKt.cleanDirectoryContents(java.io.File)'
```
when using the latest version. What I could see is that you upgraded your Kotlin version to 1.8.0-BETA: https://github.com/ryandens/javaagent-gradle-plugin/commit/5b7747d7c76e96fc91d329d9652a46c54ccd5768

When I change my Kotlin version to 1.8.0-BETA, too, the projects build. I wonder if this was intentional, since a new language version seems like a big change for a bugfix version release.

Cheers,
Ronny

**Comment by ryandens** [comment]
Thanks for the report! Fixed in #34 / 0.4.2
