### ISSUE TITLE
Caching issue - Script sometimes contains previous version number after upgrading a java agent

### ISSUE THREAD

**Issue by StefanLobbenmeierObjego** [ryandens/javaagent-gradle-plugin#41]
I have just upgraded from 
```build.gradle.kts
    javaagent("io.opentelemetry.javaagent:opentelemetry-javaagent:1.30.0")
```

to 
```build.gradle.kts
    javaagent("io.opentelemetry.javaagent:opentelemetry-javaagent:1.31.0")
```

and did a gradle assemble

Afterwards I checked 

build/scripts/servicename

and found that it still referenced the previous version:

```sh
DEFAULT_JVM_OPTS="-javaagent:$APP_HOME/agent-libs/opentelemetry-javaagent-1.30.0.jar"
```

The distTar also contained the old version number in the script, but already contained the latest java agent, so there was a mismatch and java complained it could not find the agent:

```
Error occurred during initialization of VM
agent library failed to init: instrument
Error opening zip file or JAR manifest missing : /servicefolder/agent-libs/opentelemetry-javaagent-1.30.0.jar
```

It is somewhat inconsistent to reproduce, e.g. it did not happen when I downgraded again to reproduce. So I almost did not raise this as an issue, but when I upgraded again the issue happened again.

I would like to avoid having to do a clean assemble everytime and instead be able to trust that the plugin figures out that it needs to run again.

**Comment by ryandens** [comment]
Thank you for the report! I have a reasonably good idea of the problem and should be able to release a fix in the next few days. As a temporary workaround, you should be able to add the following to your build scripts the following to properly invalidate the cache:

```kotlin
project.tasks.named(ApplicationPlugin.TASK_START_SCRIPTS_NAME, CreateStartScripts::class.java) { 
    inputs.files(configurations.named(JavaagentBasePlugin.CONFIGURATION_NAME))
}
```

That way, when the files associated with the `javaagent` dependency configuration change, the generate start scripts task will re-run

**Comment by ryandens** [comment]
I have a test that reproduced the issue you were experiencing; thanks for finding and reporting this! I just merged the fix and should have the new plugin version released tomorrow (along with an upgrade to Gradle 8.4 and some fixed deprecation warnings).

**Comment by StefanLobbenmeierObjego** [comment]
Perfect ❤️ Thank you very much
