### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by travishaagen** [ryandens/javaagent-gradle-plugin#7]
Can you please assign a license to this project? Apache or MIT, for example.

**Comment by ryandens** [comment]
Definitely! This project started out as a half-baked idea, but it worked out better than expected! Happy to help it be useful to others

**Comment by ryandens** [comment]
I kicked out another release (0.2.1) to help organizations that have automatic filtering of dependencies based on their license use this plugin! Thanks for the suggestion

**Comment by travishaagen** [comment]
Thx!
